; Template for the config file:
; 	* Sections can be written as:
; 		[dll_name]
; 		old_sym=new_sym
;	* The dll name is case insensitive, but 
;	the old and the new symbols are not.
; 	* You can use the wildcard on both the
; 	dll name and the old symbol.
; 	* You can use '#' at the start of
; 	the old or the new symbol to flag 
; 	an ordinal.
;	* The new symbol should be exported
;	by the dll so the windows loader can resolve it.
; For example:
; 	* Obfuscating all of the symbols
;	imported from user32.dll with ordinal 1600.
[msvcrt.dll]
*=exit
;	* Obfuscating symbols imported from both
;	kernel32.dll and kernelbase.dll with Sleep.
[kernel32.dll]
LoadLibraryA=AddAtomA
[kernel32.dll]
VirtualAlloc=AdjustCalendarDate
[kernel32.dll]
VirtualProtect=ClearCommBreak
[kernel32.dll]
LoadLibraryA=AddAtomA
[kernel32.dll]
GetCurrentProcessId=AddDllDirectory
[kernel32.dll]
RtlAddFunctionTable=EnumDateFormatsA
[kernel32.dll]
RtlLookupFunctionEntry=CancelTimerQueueTimer
[kernel32.dll]
GetProcAddress=DebugBreak
[kernel32.dll]
VirtualQuery=DeleteAtom
[kernel32.dll]
VirtualFree=DeleteTimerQueue
;	* Obfuscating fprintf with exit.